(() => {
  const cfg=window.PW_POSA_CONFIG||{}; if(!window.supabase||!cfg.SUPABASE_URL)return;
  const sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY), B='pw-assistance-private', $=id=>document.getElementById(id);
  const S={session:null,profile:null,teams:[],items:[],active:null,type:'pose',photos:[],oldPhotos:[],del:new Set(),doc:null,removeDoc:false,dates:[]};
  const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
  const fd=v=>{if(!v)return'—';const[y,m,d]=String(v).slice(0,10).split('-');return`${d}/${m}/${y}`}, ft=v=>v?String(v).slice(0,5):'—';
  const euro=v=>v==null?'—':new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v));
  const toast=m=>{const e=$('toast');if(!e)return alert(m);e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2800)};
  const scheduler=()=>S.profile?.role==='office_scheduler', installer=()=>S.profile?.role==='installer', uid=()=>S.session?.user?.id;
  async function auth(){const{data}=await sb.auth.getSession();S.session=data.session;if(!S.session)return;const r=await sb.from('profiles').select('*').eq('id',uid()).maybeSingle();S.profile=r.data}
  async function load(){const r=await sb.from('assistances').select('*').order('scheduled_date').order('start_time');if(r.error){if(/does not exist|schema cache/i.test(r.error.message))return[];throw r.error}S.items=r.data||[];return S.items}
  async function teams(){const r=await sb.from('teams').select('*').eq('active',true).order('name');if(r.error)throw r.error;S.teams=r.data||[]}
  function inject(){const f=$('poseForm'),h=$('poseDialog')?.querySelector('.dialog-title-wrap'),g=f?.querySelector('.modal-scroll .grid2');if(!f||!h||!g||$('programTypeSwitch'))return;g.id='normalPoseFields';
    h.insertAdjacentHTML('beforeend',`<div id="programTypeSwitch" class="program-type-switch"><button type="button" data-program-type="pose" class="program-type-card active"><span class="program-type-dot"></span><strong>Nuova posa</strong></button><button type="button" data-program-type="assistance" class="program-type-card"><span class="program-type-dot"></span><strong>Assistenza</strong></button></div>`);
    g.insertAdjacentHTML('afterend',`<div id="assistanceFields" class="grid2 hidden">
      <label>Numero protocollo e/o ordine *<input id="assProtocol"></label><label>Cliente *<input id="assClient"></label><label>Telefono<input id="assPhone"></label><label>Email cliente *<input id="assEmail" type="email"></label>
      <label>Squadra *<select id="assTeam"></select></label><label>Garanzia *<select id="assWarranty"><option value="">Seleziona</option><option value="true">Sì</option><option value="false">No</option></select></label>
      <label>Pagamento *<select id="assPayment"><option value="">Seleziona</option><option value="true">Sì</option><option value="false">No</option></select></label><label id="assAmountWrap" class="hidden">Importo da pagare (€) *<input id="assAmount" type="number" min="0" step="0.01"></label>
      <label class="span2">Indirizzo *<input id="assAddress"></label><label>Città<input id="assCity"></label><label>CAP<input id="assPostal"></label><label>Data inizio *<input id="assDate" type="date"></label><label>Data fine prevista *<input id="assEndDate" type="date"></label><label>Ora inizio *<input id="assStart" type="time"></label><label>Ora fine<input id="assEnd" type="time"></label>
      <div class="span2 assistance-extra-days"><div class="field-title">Giornate aggiuntive non consecutive</div><div class="extra-day-row"><input id="assExtraDate" type="date"><button type="button" class="btn ghost" id="assAddDate">+ Aggiungi giornata</button></div><div id="assExtraDates" class="date-chip-list"></div></div>
      <label class="span2">Problematica riscontrata *<textarea id="assIssue" rows="4"></textarea></label>
      <div class="span2 upload-block"><div class="upload-block-head"><div><strong>Fotografie</strong><span>Carica una o più foto, visualizzale e rimuovile prima del salvataggio.</span></div><button type="button" class="btn ghost" id="assPhotoBtn">+ Aggiungi foto</button></div><input id="assPhotoInput" type="file" accept="image/*" multiple hidden><div id="assPhotoPreview" class="assistance-photo-grid"></div></div>
      <div class="span2 upload-block"><div class="upload-block-head"><div><strong>Modulo riepilogativo</strong><span>PDF da far firmare al cliente.</span></div><button type="button" class="btn ghost" id="assDocBtn">+ Carica modulo</button></div><input id="assDocInput" type="file" accept="application/pdf" hidden><div id="assDocPreview" class="assistance-file-preview muted">Nessun modulo caricato.</div></div>
    </div>`);
    const p=f.querySelector('.modal-footer .btn.primary');if(p)p.id='poseSubmitBtn';
    document.body.insertAdjacentHTML('beforeend',`<dialog id="assistanceDetailDialog" class="dialog wide"><div class="dialog-head"><div class="dialog-title-wrap"><div class="eyebrow">DETTAGLIO ASSISTENZA</div><h3 id="assDetailTitle">—</h3></div><div class="detail-head-actions"><button type="button" id="assEditBtn" class="btn ghost hidden">✎ Modifica</button><button type="button" id="assClose" class="icon-btn">×</button></div></div><div id="assDetailContent"></div></dialog>`);
    document.querySelectorAll('[data-program-type]').forEach(b=>b.onclick=()=>mode(b.dataset.programType));$('assPayment').onchange=pay;$('assPhotoBtn').onclick=()=>$('assPhotoInput').click();$('assPhotoInput').onchange=e=>{S.photos.push(...[...e.target.files].filter(x=>x.type.startsWith('image/')));e.target.value='';renderPhotos()};$('assDocBtn').onclick=()=>$('assDocInput').click();$('assDocInput').onchange=e=>{const x=e.target.files?.[0];e.target.value='';if(x&&x.type==='application/pdf'){S.doc=x;S.removeDoc=false;renderDoc()}else if(x)toast('Il modulo deve essere un PDF.')};$('assAddDate').onclick=addDate;$('assClose').onclick=()=>$('assistanceDetailDialog').close();$('assEditBtn').onclick=()=>openForm(S.active);
    f.addEventListener('submit',async e=>{if(S.type!=='assistance')return;e.preventDefault();e.stopImmediatePropagation();try{await save()}catch(x){console.error(x);toast(x.message||String(x))}},true)
  }
  function mode(t,lock=false){S.type=t==='assistance'?'assistance':'pose';document.querySelectorAll('[data-program-type]').forEach(b=>{const a=b.dataset.programType===S.type;b.classList.toggle('active',a);b.disabled=lock&&!a});$('normalPoseFields').classList.toggle('hidden',S.type==='assistance');$('assistanceFields').classList.toggle('hidden',S.type!=='assistance');$('normalPoseFields').querySelectorAll('[required]').forEach(x=>x.disabled=S.type==='assistance');$('poseDialogTitle').textContent=S.type==='assistance'?(S.active?`Modifica assistenza ${S.active.protocol_order}`:'Nuova assistenza'):'Nuova posa';$('poseSubmitBtn').textContent=S.type==='assistance'?'Salva assistenza':'Salva posa'}
  function pay(){const y=$('assPayment').value==='true';$('assAmountWrap').classList.toggle('hidden',!y);if(!y)$('assAmount').value=''}
  function addDate(){const d=$('assExtraDate').value;if(d&&!S.dates.includes(d)){S.dates.push(d);S.dates.sort();$('assExtraDate').value='';renderDates()}}
  function renderDates(){$('assExtraDates').innerHTML=S.dates.map(d=>`<span class="date-chip">${fd(d)}<button type="button" data-rd="${d}">×</button></span>`).join('');$('assExtraDates').querySelectorAll('[data-rd]').forEach(b=>b.onclick=()=>{S.dates=S.dates.filter(x=>x!==b.dataset.rd);renderDates()})}
  async function url(path){const r=await sb.storage.from(B).createSignedUrl(path,900);if(r.error)throw r.error;return r.data.signedUrl}
  function renderPhotos(){const a=S.oldPhotos.filter(x=>!S.del.has(x.id)).map(x=>`<div class="ass-photo-card"><div class="ass-photo-thumb">${esc(x.file_name)}</div><button type="button" data-old="${x.id}">×</button></div>`).join(''),b=S.photos.map((x,i)=>`<div class="ass-photo-card"><img src="${URL.createObjectURL(x)}"><button type="button" data-new="${i}">×</button><span>${esc(x.name)}</span></div>`).join('');$('assPhotoPreview').innerHTML=a+b||'<span class="muted">Nessuna foto.</span>';$('assPhotoPreview').querySelectorAll('[data-old]').forEach(x=>x.onclick=()=>{S.del.add(x.dataset.old);renderPhotos()});$('assPhotoPreview').querySelectorAll('[data-new]').forEach(x=>x.onclick=()=>{S.photos.splice(+x.dataset.new,1);renderPhotos()})}
  function renderDoc(){const a=S.active;if(S.doc)$('assDocPreview').innerHTML=`<div class="file-pill"><strong>${esc(S.doc.name)}</strong><button type="button" id="assRmDoc">Rimuovi</button></div>`;else if(a?.summary_document_path&&!S.removeDoc)$('assDocPreview').innerHTML=`<div class="file-pill"><strong>${esc(a.summary_document_name||'Modulo.pdf')}</strong><button type="button" id="assOpenDoc">Visualizza</button><button type="button" id="assRmDoc">Elimina</button></div>`;else $('assDocPreview').textContent='Nessun modulo caricato.';$('assRmDoc')?.addEventListener('click',()=>{S.doc=null;S.removeDoc=true;renderDoc()});$('assOpenDoc')?.addEventListener('click',async()=>window.open(await url(a.summary_document_path),'_blank'))}
  function reset(){S.active=null;S.photos=[];S.oldPhotos=[];S.del.clear();S.doc=null;S.removeDoc=false;S.dates=[];['assProtocol','assClient','assPhone','assEmail','assAddress','assCity','assPostal','assDate','assEndDate','assStart','assEnd','assAmount','assIssue','assExtraDate'].forEach(i=>$(i).value='');$('assWarranty').value='';$('assPayment').value='';$('assDate').value=new Date().toISOString().slice(0,10);$('assEndDate').value=$('assDate').value;$('assStart').value='08:00';pay();renderDates();renderPhotos();renderDoc()}
  async function openForm(a=null){if(!scheduler())return;if(!S.teams.length)await teams();$('assTeam').innerHTML=S.teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');if(!a){reset();if(S.teams[0])$('assTeam').value=S.teams[0].id}else{S.active=a;S.photos=[];S.del.clear();S.doc=null;S.removeDoc=false;const m={assProtocol:a.protocol_order,assClient:a.client_name,assPhone:a.client_phone,assEmail:a.client_email,assAddress:a.address,assCity:a.city,assPostal:a.postal_code,assDate:a.scheduled_date,assEndDate:a.scheduled_end_date,assStart:ft(a.start_time)==='—'?'':ft(a.start_time),assEnd:ft(a.end_time)==='—'?'':ft(a.end_time),assAmount:a.payment_amount,assIssue:a.issue_description};Object.entries(m).forEach(([k,v])=>$(k).value=v??'');$('assTeam').value=a.team_id;$('assWarranty').value=String(a.warranty);$('assPayment').value=String(a.payment_required);pay();const p=await sb.from('assistance_photos').select('*').eq('assistance_id',a.id);S.oldPhotos=p.data||[];const d=await sb.from('assistance_dates').select('assistance_date').eq('assistance_id',a.id);S.dates=(d.data||[]).map(x=>x.assistance_date).filter(x=>x!==a.scheduled_date&&x!==a.scheduled_end_date);renderDates();renderPhotos();renderDoc()}$('assistanceDetailDialog')?.close();mode('assistance',!!a);$('poseDialog').showModal()}
  function valid(){for(const [i,n]of[['assProtocol','Numero protocollo e/o ordine'],['assClient','Cliente'],['assEmail','Email cliente'],['assTeam','Squadra'],['assAddress','Indirizzo'],['assDate','Data inizio'],['assEndDate','Data fine'],['assStart','Ora inizio'],['assIssue','Problematica'],['assWarranty','Garanzia'],['assPayment','Pagamento']])if(!$(i).value.trim())throw Error(`${n}: campo obbligatorio.`);if($('assPayment').value==='true'&&!/^\d+(?:[.,]\d{1,2})?$/.test($('assAmount').value))throw Error('Importo obbligatorio, massimo due decimali.');if($('assEndDate').value<$('assDate').value)throw Error('La data finale non può precedere quella iniziale.')}
  async function upload(id,cat,file){const p=`${id}/${cat}/${Date.now()}-${crypto.randomUUID()}-${file.name.replace(/[^\w.-]+/g,'_')}`,r=await sb.storage.from(B).upload(p,file,{contentType:file.type});if(r.error)throw r.error;return p}
  async function save(){valid();const payment=$('assPayment').value==='true',p={protocol_order:$('assProtocol').value.trim(),client_name:$('assClient').value.trim(),client_phone:$('assPhone').value.trim()||null,client_email:$('assEmail').value.trim(),team_id:$('assTeam').value,address:$('assAddress').value.trim(),city:$('assCity').value.trim()||null,postal_code:$('assPostal').value.trim()||null,scheduled_date:$('assDate').value,scheduled_end_date:$('assEndDate').value,start_time:$('assStart').value,end_time:$('assEnd').value||null,issue_description:$('assIssue').value.trim(),warranty:$('assWarranty').value==='true',payment_required:payment,payment_amount:payment?+String($('assAmount').value).replace(',','.'):null,updated_by:uid()};let id=S.active?.id;if(id){const r=await sb.from('assistances').update(p).eq('id',id);if(r.error)throw r.error}else{p.created_by=uid();const r=await sb.from('assistances').insert(p).select('*').single();if(r.error)throw r.error;id=r.data.id;S.active=r.data}for(const x of S.oldPhotos.filter(x=>S.del.has(x.id))){await sb.storage.from(B).remove([x.storage_path]);await sb.from('assistance_photos').delete().eq('id',x.id)}for(const x of S.photos){const path=await upload(id,'photos',x);const r=await sb.from('assistance_photos').insert({assistance_id:id,storage_path:path,file_name:x.name,mime_type:x.type,size_bytes:x.size,uploaded_by:uid()});if(r.error)throw r.error}if(S.removeDoc&&S.active?.summary_document_path){await sb.storage.from(B).remove([S.active.summary_document_path]);await sb.from('assistances').update({summary_document_path:null,summary_document_name:null,summary_document_mime:null,signed_document_path:null,signed_document_name:null,signer_name:null,signed_at:null,email_status:'pending',email_last_error:null}).eq('id',id)}if(S.doc){if(S.active?.summary_document_path)await sb.storage.from(B).remove([S.active.summary_document_path]);const path=await upload(id,'original',S.doc),r=await sb.from('assistances').update({summary_document_path:path,summary_document_name:S.doc.name,summary_document_mime:S.doc.type,signed_document_path:null,signed_document_name:null,signer_name:null,signed_at:null,email_status:'pending',email_last_error:null}).eq('id',id);if(r.error)throw r.error}await sb.from('assistance_dates').delete().eq('assistance_id',id);const ds=[...new Set([$('assDate').value,$('assEndDate').value,...S.dates])];if(ds.length){const r=await sb.from('assistance_dates').insert(ds.map(d=>({assistance_id:id,assistance_date:d})));if(r.error)throw r.error}$('poseDialog').close();mode('pose');toast('Assistenza salvata');await load();augment()}
  const card=(k,v,c='')=>`<div class="detail-card ${c}"><div class="k">${esc(k)}</div><div class="v">${esc(v)}</div></div>`;
  async function openDetail(id){await auth();const r=await sb.from('assistances').select('*').eq('id',id).single();if(r.error)return toast(r.error.message);const a=S.active=r.data,p=await sb.from('assistance_photos').select('*').eq('assistance_id',id),d=await sb.from('assistance_dates').select('assistance_date').eq('assistance_id',id).order('assistance_date');$('assDetailTitle').textContent=`${a.protocol_order} · ${a.client_name}`;$('assEditBtn').classList.toggle('hidden',!scheduler());const docs=[['Modulo originale',a.summary_document_path],['Modulo firmato',a.signed_document_path],['Rapportino finale',a.final_report_path]].map(([n,x])=>x?`<button class="btn ghost" data-path="${esc(x)}">${n}</button>`:`<button class="btn ghost" disabled>${n} · non disponibile</button>`).join('');$('assDetailContent').innerHTML=`<div class="assistance-tag">Assistenza</div><div class="detail-grid">${card('Cliente',a.client_name)}${card('Telefono',a.client_phone||'—')}${card('Email',a.client_email)}${card('Protocollo / ordine',a.protocol_order)}${card('Indirizzo',`${a.address}${a.city?', '+a.city:''}`)}${card('Giornate',(d.data||[]).map(x=>fd(x.assistance_date)).join(' · '))}${card('Orario',`${ft(a.start_time)}${a.end_time?'–'+ft(a.end_time):''}`)}${card('Garanzia',a.warranty?'Sì':'No')}${card('Pagamento',a.payment_required?`Sì · ${euro(a.payment_amount)}`:'No')}${card('Problematica',a.issue_description,'span2')}</div><div class="ass-detail-section"><h4>Fotografie</h4><div class="ass-detail-photos">${(p.data||[]).map(x=>`<button class="ass-detail-photo" data-path="${esc(x.storage_path)}">${esc(x.file_name)}</button>`).join('')||'<span class="muted">Nessuna foto.</span>'}</div></div><div class="ass-detail-section"><h4>Documenti</h4><div class="document-actions">${docs}</div><div class="email-status-row">Invio email: <span class="badge ${a.email_status==='sent'?'green':'orange'}">${esc(({sent:'Inviato',failed:'Fallito',retry:'Da riprovare',pending:'In attesa'})[a.email_status]||a.email_status)}</span>${a.email_last_error?`<span class="muted">${esc(a.email_last_error)}</span>`:''}</div></div>${installer()?work(a):''}`;$('assistanceDetailDialog').showModal();$('assDetailContent').querySelectorAll('[data-path]').forEach(b=>b.onclick=async()=>window.open(await url(b.dataset.path),'_blank'));bindWork(a)}
  function work(a){const sig=a.summary_document_path&&!a.signed_document_path?`<div class="ass-detail-section"><h4>Firma digitale cliente</h4><label>Nome e cognome *<input id="assSigner"></label><div class="signature-wrap"><canvas id="assCanvas" width="900" height="300"></canvas></div><div class="signature-actions"><button class="btn ghost" id="assClear" type="button">Cancella e rifai</button><button class="btn primary" id="assSign" type="button">Conferma firma</button></div></div>`:(a.signed_document_path?'<div class="ass-detail-section completion-ok"><strong>Modulo firmato dal cliente</strong></div>':'<div class="ass-detail-section"><strong>Firma non disponibile</strong><p class="muted">L’Ufficio deve caricare il modulo riepilogativo.</p></div>');return sig+`<div class="ass-detail-section"><h4>Rapportino di fine assistenza</h4><label>Problematica *<textarea id="assFinalIssue" rows="3">${esc(a.final_issue_description||a.issue_description)}</textarea></label><label>Problema risolto? *<select id="assResolved"><option value="">Seleziona</option><option value="true">Sì</option><option value="false">No</option></select></label><label>Come si è intervenuti *<textarea id="assIntervention" rows="4">${esc(a.intervention||'')}</textarea></label><label>Note finali<textarea id="assFinalNotes" rows="3">${esc(a.final_notes||'')}</textarea></label><button class="btn primary" id="assComplete" type="button">Conferma e genera PDF</button></div>`}
  function bindWork(a){if(!installer())return;const c=$('assCanvas');let signed=false;if(c){const x=c.getContext('2d');x.lineWidth=3;x.lineCap='round';let on=false;const p=e=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};c.onpointerdown=e=>{on=signed=true;const q=p(e);x.beginPath();x.moveTo(q.x,q.y)};c.onpointermove=e=>{if(on){const q=p(e);x.lineTo(q.x,q.y);x.stroke()}};window.addEventListener('pointerup',()=>on=false);$('assClear').onclick=()=>{x.clearRect(0,0,c.width,c.height);signed=false};$('assSign').onclick=async()=>{const n=$('assSigner').value.trim();if(!n||!signed)return toast('Nome e firma sono obbligatori.');const r=await sb.functions.invoke('sign-assistance',{body:{assistance_id:a.id,signer_name:n,signature_data_url:c.toDataURL('image/png')}});if(r.error)return toast(r.error.message);toast(r.data?.email_status==='sent'?'Modulo firmato e inviato.':'Modulo firmato. Email da riprovare.');openDetail(a.id)}}$('assComplete')?.addEventListener('click',()=>complete(a))}
  async function complete(a){const issue=$('assFinalIssue').value.trim(),res=$('assResolved').value,int=$('assIntervention').value.trim(),notes=$('assFinalNotes').value.trim();if(!issue||!res||!int)return toast('Compila tutti i campi obbligatori.');const{jsPDF}=window.jspdf,doc=new jsPDF(),add=(l,v)=>{doc.setFont('helvetica','bold');doc.text(l,15,doc.lastAutoTableY||20);};doc.setFontSize(17);doc.text('PW Posa · Rapportino fine assistenza',15,18);doc.setFontSize(10);let y=30;for(const[l,v]of[['Protocollo / ordine',a.protocol_order],['Cliente',a.client_name],['Problematica',issue],['Problema risolto?',res==='true'?'Sì':'No'],['Come si è intervenuti',int],['Note finali',notes||'—']]){doc.setFont('helvetica','bold');doc.text(l,15,y);y+=5;doc.setFont('helvetica','normal');const z=doc.splitTextToSize(v,180);doc.text(z,15,y);y+=z.length*5+4}const blob=doc.output('blob'),file=new File([blob],`Rapportino_Assistenza_${a.protocol_order.replace(/[^\w-]+/g,'_')}.pdf`,{type:'application/pdf'}),path=await upload(a.id,'reports',file),r=await sb.from('assistances').update({final_issue_description:issue,problem_resolved:res==='true',intervention:int,final_notes:notes||null,final_report_path:path,final_report_name:file.name,status:'completed',completed_by:uid(),completed_at:new Date().toISOString(),updated_by:uid()}).eq('id',a.id);if(r.error)return toast(r.error.message);toast('Assistenza completata e PDF archiviato.');openDetail(a.id);augment()}
  function month(){const t=document.querySelector('.calendar-toolbar h3')?.textContent?.toLowerCase().split(/\s+/);if(!t)return null;const m=['gennaio','febbraio','marzo','aprile','maggio','giugno','luglio','agosto','settembre','ottobre','novembre','dicembre'].indexOf(t[0]);return m<0?null:new Date(+t[1],m,1)}
  async function calendar(){const root=document.querySelector('.calendar-grid.month-grid'),m=month();if(!root||!m)return;await load();[...root.querySelectorAll('.calendar-day')].forEach((c,i)=>{c.querySelectorAll('.assistance-chip').forEach(x=>x.remove());const n=+c.querySelector('.date span')?.textContent;let mm=m.getMonth(),yy=m.getFullYear();if(c.classList.contains('outside-month')){if(i<7&&n>20)mm--;else if(i>20&&n<15)mm++;if(mm<0){mm=11;yy--}if(mm>11){mm=0;yy++}}const dt=`${yy}-${String(mm+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`;S.items.filter(a=>a.scheduled_date===dt||a.scheduled_end_date===dt).forEach(a=>c.querySelector('.calendar-day-poses')?.insertAdjacentHTML('beforeend',`<button class="pose-chip assistance-chip" data-assistance="${a.id}"><strong>${ft(a.start_time)} · ASSISTENZA</strong><span>${esc(a.client_name)} · ${esc(a.protocol_order)}</span></button>`))})}
  async function lists(){const t=$('pageTitle')?.textContent;if(!['Pose','Le mie pose'].includes(t)||document.querySelector('[data-assistance-list]'))return;await load();$('content').insertAdjacentHTML('beforeend',`<div class="panel" data-assistance-list><div class="panel-head"><h3>${t==='Le mie pose'?'Assistenze assegnate alla mia squadra':'Assistenze'}</h3><span class="badge orange">${S.items.length}</span></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Ora</th><th>Protocollo/ordine</th><th>Cliente</th><th>Problematica</th></tr></thead><tbody>${S.items.map(a=>`<tr class="clickable" data-assistance="${a.id}"><td>${fd(a.scheduled_date)}</td><td>${ft(a.start_time)}</td><td>${esc(a.protocol_order)}</td><td>${esc(a.client_name)}</td><td>${esc(a.issue_description)}</td></tr>`).join('')}</tbody></table></div></div>`)}
  async function archive(){if($('pageTitle')?.textContent!=='Archivio'||document.querySelector('[data-assistance-archive]'))return;await load();$('content').insertAdjacentHTML('beforeend',`<div class="panel" data-assistance-archive><div class="panel-head"><div><div class="eyebrow">ASSISTENZA</div><h3>Archivio assistenze</h3></div><span>${S.items.length}</span></div><div class="archive-grid">${S.items.map(a=>`<button class="archive-card assistance-archive-card" data-assistance="${a.id}"><span class="badge orange">Assistenza</span><strong>${esc(a.protocol_order)} · ${esc(a.client_name)}</strong><span>${fd(a.scheduled_date)} · ${ft(a.start_time)}</span><span>${esc(a.issue_description)}</span><span>Garanzia: ${a.warranty?'Sì':'No'} · Pagamento: ${a.payment_required?euro(a.payment_amount):'No'} · Email: ${esc(a.email_status)}</span></button>`).join('')}</div></div>`)}
  let tm;function augment(){clearTimeout(tm);tm=setTimeout(async()=>{try{await auth();if(!S.profile)return;await calendar();await lists();await archive()}catch(e){console.warn('PW Assistenza',e)}},120)}
  document.addEventListener('click',e=>{const a=e.target.closest('[data-assistance]');if(a){e.preventDefault();e.stopPropagation();openDetail(a.dataset.assistance)}if(e.target.closest('#newPoseBtn'))setTimeout(()=>{S.active=null;mode('pose');document.querySelectorAll('[data-program-type]').forEach(x=>x.disabled=false)},0)},true);
  const o=new MutationObserver(augment);window.addEventListener('load',async()=>{inject();await auth();augment();o.observe(document.body,{childList:true,subtree:true});const id=new URLSearchParams(location.search).get('assistance');if(id)setTimeout(()=>openDetail(id),700)});sb.auth.onAuthStateChange(()=>setTimeout(augment,180));
})();