(() => {
  const cfg=window.PW_POSA_CONFIG||{};
  if(!window.supabase||!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY)return;
  const sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY), B='pw-ddt-private';
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
  const toast=m=>{const e=$('toast');if(!e)return alert(m);e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3600)};
  const state={profile:null,pose:{file:null,areas:null,existing:null},assistance:{file:null,areas:null,existing:null},currentPose:null,currentAssistance:null,setupKind:'pose',setupPdf:null,setupPage:1,setupRole:'installer',signDdt:null};
  const kindState=k=>state[k==='assistance'?'assistance':'pose'];
  const validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'').trim());
  const mode=()=>!$('assistanceFields')?.classList.contains('hidden')?'assistance':'pose';

  async function getProfile(){if(state.profile)return state.profile;const {data:{session}}=await sb.auth.getSession();if(!session)return null;const r=await sb.from('profiles').select('*').eq('id',session.user.id).single();if(r.error)throw r.error;state.profile=r.data;return r.data}
  async function getDoc(kind,id){if(!id)return null;const col=kind==='assistance'?'assistance_id':'pose_id';const r=await sb.from('ddt_documents').select('*').eq(col,id).maybeSingle();if(r.error)throw r.error;return r.data}
  async function fileBlob(path){const r=await sb.storage.from(B).download(path);if(r.error)throw r.error;return r.data}
  async function signedUrl(path){const r=await sb.storage.from(B).createSignedUrl(path,600);if(r.error)throw r.error;return r.data.signedUrl}
  function defaultAreas(page){return{installer:{page,x:.55,y:.84,w:.20,h:.09},client:{page,x:.78,y:.84,w:.20,h:.09}}}

  function inject(){
    const pose=$('normalPoseFields'),ass=$('assistanceFields');if(!pose||!ass||$('poseDdtBlock'))return;
    const phone=$('clientPhone')?.closest('label');
    if(phone&&!$('poseClientEmail'))phone.insertAdjacentHTML('afterend','<label>Email cliente *<input id="poseClientEmail" type="email" required placeholder="cliente@email.it"></label>');
    pose.insertAdjacentHTML('beforeend',block('pose',true));
    ass.insertAdjacentHTML('beforeend',block('assistance',false));
    document.body.insertAdjacentHTML('beforeend',`<dialog id="ddtSetupDialog" class="dialog wide"><div class="dialog-head"><div><div class="eyebrow">DDT</div><h3>Imposta aree firma</h3></div><button class="icon-btn" type="button" id="ddtSetupClose">×</button></div><div style="padding:18px 24px 24px"><div class="ddt-setup-tools"><label>Pagina firme <input id="ddtPage" type="number" min="1" value="1" style="width:90px"></label><button type="button" class="btn ghost active" id="ddtSetInstaller">Firma posatore</button><button type="button" class="btn ghost" id="ddtSetClient">Firma cliente</button><span class="muted">Seleziona il tipo di firma e clicca sul punto del PDF.</span></div><div id="ddtStageWrap" style="overflow:auto;text-align:center"><div id="ddtStage" class="ddt-setup-stage"><canvas id="ddtCanvas"></canvas><div id="ddtAreaInstaller" class="ddt-area installer"></div><div id="ddtAreaClient" class="ddt-area client"></div></div></div><div class="dialog-actions" style="padding:18px 0 0"><button type="button" class="btn primary" id="ddtSetupSave">Salva posizioni firme</button></div></div></dialog><dialog id="ddtSignDialog" class="dialog wide"><div class="dialog-head"><div><div class="eyebrow">DDT</div><h3>Firma documento di trasporto</h3></div><button class="icon-btn" type="button" id="ddtSignClose">×</button></div><div style="padding:18px 24px 24px"><p id="ddtSignInfo" class="muted"></p><div class="ddt-sign-grid"><div class="ddt-sign-box"><strong>Firma posatore</strong><canvas id="ddtInstallerSign" width="700" height="220"></canvas><button type="button" class="btn ghost" data-clear-sign="ddtInstallerSign">Cancella firma</button></div><div class="ddt-sign-box"><strong>Firma cliente</strong><canvas id="ddtClientSign" width="700" height="220"></canvas><button type="button" class="btn ghost" data-clear-sign="ddtClientSign">Cancella firma</button></div></div><div class="dialog-actions" style="padding:18px 0 0"><button type="button" class="btn primary" id="ddtConfirmSign">Conferma firme e invia copia al cliente</button></div></div></dialog>`);
    bindUpload('pose');bindUpload('assistance');
    $('ddtSetupClose').onclick=()=>$('ddtSetupDialog').close();$('ddtSignClose').onclick=()=>$('ddtSignDialog').close();
    $('ddtSetInstaller').onclick=()=>setRole('installer');$('ddtSetClient').onclick=()=>setRole('client');$('ddtPage').onchange=()=>renderSetupPage(+($('ddtPage').value||1));
    $('ddtCanvas').addEventListener('click',placeArea);$('ddtSetupSave').onclick=()=>$('ddtSetupDialog').close();
    document.querySelectorAll('[data-clear-sign]').forEach(b=>b.onclick=()=>clearSign($(b.dataset.clearSign)));
    makeSignatureCanvas($('ddtInstallerSign'));makeSignatureCanvas($('ddtClientSign'));$('ddtConfirmSign').onclick=confirmSign;
  }
  function block(kind,required){const p=kind==='pose'?'pose':'ass';return `<div id="${p}DdtBlock" class="span2 ddt-upload-block"><div class="ddt-upload-head"><div><strong>DDT ${required?'<span class="ddt-required">*</span>':''}</strong><span>${required?'Obbligatorio per la posa. Carica il PDF e verifica le due aree firma.':'Facoltativo per l’assistenza. Caricalo solo quando serve per materiali o sostituzioni.'}</span></div><button type="button" class="btn ghost" id="${p}DdtBtn">+ Aggiungi DDT</button></div><input id="${p}DdtInput" type="file" accept="application/pdf" hidden><div id="${p}DdtPreview" class="ddt-preview"><span class="muted">Nessun DDT caricato.</span></div></div>`}
  function bindUpload(kind){const p=kind==='pose'?'pose':'ass';$(p+'DdtBtn').onclick=()=>$(p+'DdtInput').click();$(p+'DdtInput').onchange=async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;if(f.type!=='application/pdf'&&!/\.pdf$/i.test(f.name))return toast('Il DDT deve essere un PDF.');const s=kindState(kind);s.file=f;s.existing=s.existing||null;try{const pdf=await loadPdf(f);const page=pdf.numPages;s.areas=defaultAreas(page);renderPreview(kind);await openSetup(kind,f)}catch(err){console.error(err);toast('Impossibile leggere il PDF: '+err.message)}}}
  function renderPreview(kind){const s=kindState(kind),p=kind==='pose'?'pose':'ass',e=s.existing,name=s.file?.name||e?.original_name;if(!name){$(p+'DdtPreview').innerHTML='<span class="muted">Nessun DDT caricato.</span>';return}const signed=e?.signed_path?'<span class="badge green">Firmato</span>':'';$(p+'DdtPreview').innerHTML=`<div><strong>${esc(name)}</strong><div class="muted">Aree firma: ${s.areas?.installer&&s.areas?.client?'impostate':'da impostare'}</div></div><div style="display:flex;gap:8px;flex-wrap:wrap">${signed}<button type="button" class="btn ghost" data-ddt-configure="${kind}">Modifica aree firma</button>${e?.original_path?`<button type="button" class="btn ghost" data-ddt-open="${kind}">Apri PDF</button>`:''}</div>`;$(p+'DdtPreview').querySelector('[data-ddt-configure]')?.addEventListener('click',()=>openSetup(kind));$(p+'DdtPreview').querySelector('[data-ddt-open]')?.addEventListener('click',async()=>window.open(await signedUrl(e.original_path),'_blank','noopener'))}
  async function loadPdf(fileOrBlob){if(!window.pdfjsLib)throw Error('Lettore PDF non disponibile');const buf=await fileOrBlob.arrayBuffer();return window.pdfjsLib.getDocument({data:buf}).promise}
  async function openSetup(kind,localFile=null){state.setupKind=kind;const s=kindState(kind);let source=localFile||s.file;if(!source&&s.existing?.original_path)source=await fileBlob(s.existing.original_path);if(!source)return toast('Carica prima il DDT.');state.setupPdf=await loadPdf(source);const page=Math.min(Math.max(1,s.areas?.installer?.page||s.areas?.client?.page||state.setupPdf.numPages),state.setupPdf.numPages);$('ddtPage').max=state.setupPdf.numPages;$('ddtPage').value=page;setRole('installer');await renderSetupPage(page);$('ddtSetupDialog').showModal()}
  function setRole(role){state.setupRole=role;$('ddtSetInstaller').classList.toggle('active',role==='installer');$('ddtSetClient').classList.toggle('active',role==='client')}
  async function renderSetupPage(pageNum){if(!state.setupPdf)return;pageNum=Math.min(Math.max(1,pageNum),state.setupPdf.numPages);state.setupPage=pageNum;$('ddtPage').value=pageNum;const page=await state.setupPdf.getPage(pageNum),base=page.getViewport({scale:1}),scale=Math.min(1.4,900/base.width),vp=page.getViewport({scale});const c=$('ddtCanvas'),ctx=c.getContext('2d');c.width=vp.width;c.height=vp.height;await page.render({canvasContext:ctx,viewport:vp}).promise;drawAreas()}
  function placeArea(e){const c=$('ddtCanvas'),r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height,w=.22,h=.085;const a={page:state.setupPage,x:Math.max(0,Math.min(1-w,x-w/2)),y:Math.max(0,Math.min(1-h,y-h/2)),w,h};const s=kindState(state.setupKind);s.areas=s.areas||defaultAreas(state.setupPage);s.areas[state.setupRole]=a;drawAreas();renderPreview(state.setupKind)}
  function drawAreas(){const s=kindState(state.setupKind),stage=$('ddtStage');for(const [role,id] of [['installer','ddtAreaInstaller'],['client','ddtAreaClient']]){const el=$(id),a=s.areas?.[role];if(!a||a.page!==state.setupPage){el.style.display='none';continue}el.style.display='block';el.style.left=(a.x*100)+'%';el.style.top=(a.y*100)+'%';el.style.width=(a.w*100)+'%';el.style.height=(a.h*100)+'%'}stage.style.width=$('ddtCanvas').width+'px'}

  async function hydratePoseForm(){const id=$('poseId')?.value||null;state.currentPose=id;const s=state.pose;s.file=null;s.existing=null;s.areas=null;if(id){const [pr,doc]=await Promise.all([sb.from('poses').select('client_email').eq('id',id).single(),getDoc('pose',id)]);if(!pr.error&&$('poseClientEmail'))$('poseClientEmail').value=pr.data?.client_email||'';s.existing=doc;s.areas=doc?{installer:doc.installer_signature_area,client:doc.client_signature_area}:null}else if($('poseClientEmail'))$('poseClientEmail').value='';renderPreview('pose')}
  async function hydrateAssistanceForm(){const s=state.assistance;s.file=null;s.existing=null;s.areas=null;if(state.currentAssistance){const doc=await getDoc('assistance',state.currentAssistance);s.existing=doc;s.areas=doc?{installer:doc.installer_signature_area,client:doc.client_signature_area}:null}renderPreview('assistance')}

  async function validatePoseBeforeSave(existingId){inject();const email=$('poseClientEmail')?.value.trim();if(!validEmail(email))throw Error('Email cliente: inserisci un indirizzo valido.');const s=state.pose;if(existingId&&!s.existing)s.existing=await getDoc('pose',existingId);if(!s.file&&!s.existing)throw Error('DDT obbligatorio: carica il documento prima di salvare la posa.');const areas=s.areas||{installer:s.existing?.installer_signature_area,client:s.existing?.client_signature_area};if(!areas?.installer||!areas?.client)throw Error('Imposta entrambe le aree firma del DDT: posatore e cliente.');return true}
  async function saveDoc(kind,parentId){const s=kindState(kind);let existing=s.existing||await getDoc(kind,parentId);if(!s.file){if(existing&&s.areas&&(JSON.stringify(s.areas.installer)!==JSON.stringify(existing.installer_signature_area)||JSON.stringify(s.areas.client)!==JSON.stringify(existing.client_signature_area))){const u=await sb.from('ddt_documents').update({installer_signature_area:s.areas.installer,client_signature_area:s.areas.client,signature_page:s.areas.client?.page||s.areas.installer?.page||1}).eq('id',existing.id).select('*').single();if(u.error)throw u.error;s.existing=u.data}return s.existing||existing}
    const {data:{session}}=await sb.auth.getSession();if(!session)throw Error('Sessione scaduta');const id=existing?.id||crypto.randomUUID(),safe=s.file.name.replace(/[^\w.-]+/g,'_'),path=`${id}/original/${Date.now()}-${safe}`;const up=await sb.storage.from(B).upload(path,s.file,{contentType:'application/pdf'});if(up.error)throw up.error;const payload={original_path:path,original_name:s.file.name,original_mime:'application/pdf',signature_page:s.areas?.client?.page||s.areas?.installer?.page||1,installer_signature_area:s.areas?.installer,client_signature_area:s.areas?.client,signed_path:null,signed_name:null,signed_at:null,signed_by:null,email_status:'pending',email_last_error:null,created_by:session.user.id};let r;if(existing)r=await sb.from('ddt_documents').update(payload).eq('id',existing.id).select('*').single();else{payload.id=id;if(kind==='pose')payload.pose_id=parentId;else payload.assistance_id=parentId;r=await sb.from('ddt_documents').insert(payload).select('*').single()}if(r.error){await sb.storage.from(B).remove([path]);throw r.error}if(existing?.original_path&&existing.original_path!==path)await sb.storage.from(B).remove([existing.original_path]);if(existing?.signed_path)await sb.storage.from(B).remove([existing.signed_path]);s.existing=r.data;s.file=null;renderPreview(kind);return r.data}
  async function saveForPose(id){return saveDoc('pose',id)}
  async function saveForAssistance(id){if(!state.assistance.file&&!state.assistance.existing)return null;return saveDoc('assistance',id)}
  function getPoseEmail(){return $('poseClientEmail')?.value.trim()||''}

  function makeSignatureCanvas(c){if(!c)return;const ctx=c.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#111';let drawing=false,last=null;c.dataset.signed='0';const pt=e=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};c.addEventListener('pointerdown',e=>{drawing=true;last=pt(e);c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drawing)return;const p=pt(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;c.dataset.signed='1'});const end=()=>{drawing=false;last=null};c.addEventListener('pointerup',end);c.addEventListener('pointercancel',end)}
  function clearSign(c){const x=c?.getContext('2d');if(x&&c){x.clearRect(0,0,c.width,c.height);c.dataset.signed='0'}}
  async function openSign(ddt,label){state.signDdt=ddt;clearSign($('ddtInstallerSign'));clearSign($('ddtClientSign'));$('ddtSignInfo').textContent=`${label}. Sono necessarie entrambe le firme. Al termine una copia del DDT firmato verrà inviata automaticamente al cliente.`;$('ddtSignDialog').showModal()}
  async function confirmSign(){const d=state.signDdt;if(!d)return;if($('ddtInstallerSign').dataset.signed!=='1')return toast('Manca la firma del posatore.');if($('ddtClientSign').dataset.signed!=='1')return toast('Manca la firma del cliente.');const btn=$('ddtConfirmSign'),old=btn.textContent;btn.disabled=true;btn.textContent='Creazione DDT firmato…';try{if(!window.PDFLib)throw Error('Editor PDF non disponibile');const original=await fileBlob(d.original_path),pdf=await window.PDFLib.PDFDocument.load(await original.arrayBuffer());for(const [role,canvas] of [['installer',$('ddtInstallerSign')],['client',$('ddtClientSign')]]){const a=role==='installer'?d.installer_signature_area:d.client_signature_area;if(!a)throw Error(`Area firma ${role==='installer'?'posatore':'cliente'} non configurata dall’Ufficio`);const page=pdf.getPage(Math.max(0,Math.min(pdf.getPageCount()-1,(a.page||1)-1))),{width,height}=page.getSize(),png=await pdf.embedPng(canvas.toDataURL('image/png'));page.drawImage(png,{x:a.x*width,y:height-(a.y+a.h)*height,width:a.w*width,height:a.h*height})}const bytes=await pdf.save(),blob=new Blob([bytes],{type:'application/pdf'}),name=`${String(d.original_name||'DDT').replace(/\.pdf$/i,'')}_FIRMATO.pdf`,path=`${d.id}/signed/${Date.now()}-${name.replace(/[^\w.-]+/g,'_')}`;const up=await sb.storage.from(B).upload(path,blob,{contentType:'application/pdf'});if(up.error)throw up.error;const {data:{session}}=await sb.auth.getSession();const u=await sb.from('ddt_documents').update({signed_path:path,signed_name:name,signed_at:new Date().toISOString(),signed_by:session.user.id,email_status:'pending',email_last_error:null}).eq('id',d.id);if(u.error)throw u.error;btn.textContent='Invio email…';const mail=await sb.functions.invoke('send-ddt-email',{body:{ddt_id:d.id}});if(mail.error){toast('DDT firmato salvato. Invio email da riprovare.');console.error(mail.error)}else toast('DDT firmato e inviato al cliente.');$('ddtSignDialog').close();setTimeout(()=>location.reload(),700)}catch(e){console.error(e);toast(e.message||String(e))}finally{btn.disabled=false;btn.textContent=old}}

  async function renderDetail(kind,id,host){if(!id||!host)return;const profile=await getProfile(),d=await getDoc(kind,id);host.querySelector('[data-ddt-card]')?.remove();const parent=kind==='pose'?await sb.from('poses').select('job_number,client_name,client_email').eq('id',id).single():await sb.from('assistances').select('protocol_order,client_name,client_email').eq('id',id).single();const p=parent.data||{},label=kind==='pose'?`Posa ${p.job_number||''}`:`Assistenza ${p.protocol_order||''}`;const card=document.createElement('div');card.className='ddt-card';card.dataset.ddtCard='1';if(!d){card.innerHTML=`<div class="ddt-card-head"><div><strong>DDT</strong><div class="muted">${kind==='pose'?'DDT non disponibile. Contatta l’Ufficio.':'Nessun DDT previsto per questa assistenza.'}</div></div></div>`;host.appendChild(card);return}card.innerHTML=`<div class="ddt-card-head"><div><strong>DDT</strong><div class="muted">${esc(d.original_name)}</div></div><span class="badge ${d.signed_path?'green':'orange'}">${d.signed_path?'Firmato':'Da firmare'}</span></div><div class="ddt-actions"><button type="button" class="btn ghost" data-ddt-detail-open>Apri originale</button>${d.signed_path?'<button type="button" class="btn ghost" data-ddt-signed-open>Apri firmato</button>':''}${profile?.role==='installer'&&!d.signed_path?'<button type="button" class="btn primary" data-ddt-sign>Firma DDT</button>':''}</div><div class="ddt-email-status">Email cliente: ${esc(p.client_email||'—')} · Stato invio: ${esc(d.email_status||'pending')}</div>`;host.appendChild(card);card.querySelector('[data-ddt-detail-open]').onclick=async()=>window.open(await signedUrl(d.original_path),'_blank','noopener');card.querySelector('[data-ddt-signed-open]')?.addEventListener('click',async()=>window.open(await signedUrl(d.signed_path),'_blank','noopener'));card.querySelector('[data-ddt-sign]')?.addEventListener('click',()=>openSign(d,`${label} · ${p.client_name||''}`))}

  document.addEventListener('click',e=>{const a=e.target.closest('[data-assistance]');if(a?.dataset.assistance)state.currentAssistance=a.dataset.assistance;const p=e.target.closest('[data-pose]');if(p?.dataset.pose)state.currentPose=p.dataset.pose;if(e.target.closest('#newPoseBtn')){state.currentAssistance=null;state.currentPose=null;state.pose.file=null;state.pose.existing=null;state.pose.areas=null;state.assistance.file=null;state.assistance.existing=null;state.assistance.areas=null}setTimeout(()=>{if(state.currentPose&&$('detailDialog')?.open)renderDetail('pose',state.currentPose,$('detailContent')).catch(console.warn);if(state.currentAssistance&&$('assistanceDetailDialog')?.open)renderDetail('assistance',state.currentAssistance,$('assDetailContent')).catch(console.warn)},280)},true);
  const obs=()=>{const dlg=$('poseDialog');if(dlg)new MutationObserver(()=>{if(!dlg.open)return;setTimeout(()=>{if(mode()==='pose')hydratePoseForm().catch(console.warn);else hydrateAssistanceForm().catch(console.warn)},120)}).observe(dlg,{attributes:true,attributeFilter:['open']})};
  inject();obs();window.PW_DDT={validatePoseBeforeSave,saveForPose,saveForAssistance,getPoseEmail,hydrateAssistanceForm};
})();